# Generated by Django 4.1.7 on 2023-02-28 04:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('b_id', models.IntegerField(default='-1')),
                ('title', models.CharField(blank=True, max_length=1024, null=True)),
                ('content', models.CharField(max_length=250)),
                ('image', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Reference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('occurrence', models.IntegerField(default='-1')),
                ('book_reference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mytig.book')),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mytig.word')),
            ],
            options={
                'ordering': ('occurrence',),
            },
        ),
    ]
